name: cluster_fipy
channels:
  - conda-forge
  - defaults
dependencies:
  - datreant.core=0.7.1=py27_0
  - future=0.18.0=py27_0
  - gitpython=2.1.7=py27_0
  - gmsh=3.0.6=he2a7a22_2
  - jupyter=1.0.0=py_2
  - matplotlib=2.2.4=py27_1
  - mayavi=4.7.1=py27h7eb8c7e_2
  - mpi4py=3.0.2=py27hcf07815_0
  - numpy=1.16.4=py27h95a1406_0
  - openblas=0.2.20=8
  - pandas=0.24.2=py27hb3f55d8_0
  - pip=19.2.3=py27_0
  - pysparse=1.3.dev=py27h3010b51_1003
  - python=2.7.15=h5a48372_1009
  - pytrilinos=12.10.1=py27h7127e17_2
  - pyyaml=5.1.2=py27h516909a_0
  - scipy=1.2.1=py27h921218d_2
  - setuptools=41.4.0=py27_0
 - pip:
    - scikit-fmm==2019.1.30
prefix: /tmp/guyer/miniconda2/envs/cluster_fipy

